import "./lib/win-console.mjs";
import fs from "node:fs";

const map = JSON.parse(fs.readFileSync("payload/hardcoded-zh.json", "utf8"));
const extra = {
  "Toggle Primary Side Bar Visibility": "切换主侧边栏的显示",
  "Toggle Agents": "切换 Agent",
  "Toggle Agents visibility": "切换 Agent 的显示",
  "Open Browser": "打开浏览器",
  "Hide Prompt Bar": "隐藏提示栏",
  "Close Prompt Bar": "关闭提示栏",
  "Next Prompt Bar": "下一个提示栏",
  "Open model toggle": "打开模型切换",
  "Open File Diff": "打开文件差异",
  "Open Tab as Editor": "将标签页作为编辑器打开",
  "Open Terminal in Worktree": "在 Worktree 中打开终端",
  "Open Local Agent Logs": "打开本地 Agent 日志",
  "Open in Web": "在网页中打开",
  "Open File": "打开文件",
  "Open Branch Menu": "打开分支菜单",
  "Next chat tab": "下一个聊天标签页",
  "Previous chat tab": "上一个聊天标签页",
  "Select Next Chat": "选择下一个聊天",
  "Select Previous Chat": "选择上一个聊天",
  "Focus Chat Followup": "聚焦聊天跟进",
  "Delete Old Chats...": "删除旧聊天...",
  "Close All Tabs": "关闭全部标签页",
  "Close Other Tabs": "关闭其他标签页",
  "Close Tab": "关闭标签页",
  "Cancel Generation": "取消生成",
  "Check for Update": "检查更新",
  "Attempt Update": "尝试更新",
  "Generate an Image": "生成图片",
  "Share Canvas": "分享 Canvas",
  "Reset Mode to Default": "将模式重置为默认",
  "Switch to model": "切换到模型",
  "Switch to Model Slug": "切换到指定模型",
  "Add model to switcher": "将模型添加到切换器",
  "Disable Autocompletes": "禁用自动补全",
  "Connect Slack": "连接 Slack",
  "Sign Out of GitHub": "退出 GitHub",
  "Open in Editor": "在编辑器中打开",
  "Add to Chat": "添加到聊天",
  "Add to Side Chat": "添加到侧边聊天",
  "Add an agent to get started": "添加一个 Agent 开始工作",
  "Add new stuff": "添加新内容",
  "Add plugins": "添加插件",
  "Add Skills": "添加技能",
  "Add your own MCP server": "添加你自己的 MCP 服务器",
  "Access Settings": "打开设置",
  "Agent Instructions": "Agent 指令",
  "Agent Mode": "Agent 模式",
  "Ask Mode": "提问模式",
  "Browse Canvases": "浏览 Canvas",
  "Browse MCPs": "浏览 MCP",
  "Build Locally": "在本地构建",
  "Build in Cloud": "在云端构建",
  "Build in New Agent": "在新 Agent 中构建",
  "Chat conversations": "聊天对话",
  "Chat history": "聊天记录",
  "Archive Prior Chats": "归档先前的聊天",
  "Add Another Account": "添加其他账户",
  "Appearance": "外观",
  "Local": "本地",
  "Cloud": "云端",
  "Preferences": "首选项",
  "Keyboard Shortcuts": "键盘快捷方式",
  "Layout": "布局",
  "Status Bar": "状态栏",
  "Notifications": "通知",
  "Window Restoration": "窗口还原",
  "Typography": "排版",
  "Motion": "动效",
  "Colors": "颜色",
  "Intensity": "强度",
  "Reduce Transparency": "降低透明度",
  "Follow System Color Scheme": "跟随系统配色",
  "Menu Bar Icon": "菜单栏图标",
  "System Tray Icon": "系统托盘图标",
  "Completion Sound": "完成提示音",
  "Queue Messages": "排队消息",
  "Follow-Up Prompt Suggestions": "跟进提示建议",
  "Voice Submit Keywords": "语音提交关键词",
  "Web Fetch Tool": "网页抓取工具",
  "Toolbar on Selection": "选区工具栏",
  "Terminal Hint": "终端提示",
  "Preview Box for Terminal Cmd/Ctrl+K": "终端 Cmd/Ctrl+K 预览框",
  "Terminal and Editing": "终端与编辑",
  "Execution and Approvals": "执行与批准",
  "Monthly Limit": "每月限额",
  "Public Profile": "公开资料",
  "First Name": "名",
  "Last Name": "姓",
  "Handle": "用户名",
  "Profile Image": "头像",
  "Links": "链接",
  "Verify Extension Signatures": "验证扩展签名",
  "Ignore Files": "忽略文件",
  "Codebase": "代码库",
  "Pull Requests": "拉取请求",
  "Attribution": "归属",
  "Branch Prefix": "分支前缀",
  "Gateway": "网关",
  "Required Domains": "必需域名",
  "Update Access": "更新访问",
  "Cleanup": "清理",
  "LSP": "语言服务",
  "Maximum Local LSP Workspaces": "本地 LSP 工作区上限",
  "Maximum Remote LSP Workspaces": "远程 LSP 工作区上限",
  "Marketplace Access": "市场访问",
  "Enable Auto Refresh": "启用自动刷新",
  "Allow Members to Publish": "允许成员发布",
  "Serve Marketplace From Cursor": "由 Cursor 提供市场服务",
  "Remove Marketplace": "移除市场",
  "Code Block Word Wrap": "代码块自动换行",
  "Legacy Terminal Tool": "旧版终端工具",
  "Open Customize": "打开自定义",
  "Upgrade to Pro": "升级到 Pro",
  "Cursor Tab": "Cursor Tab",
  "Conversation": "对话",
  "Sign In": "登录",
  "Suggestions While Commenting": "在注释中提供建议",
  "Ignore Files in .cursorignore": "在 .cursorignore 中忽略文件",
  "Team-Level Repository Control": "团队级仓库控制",
  "Use Team AWS Bedrock": "使用团队 AWS Bedrock",
  "Use OpenAI API Key": "使用 OpenAI API 密钥",
  "Override OpenAI Base URL": "覆盖 OpenAI Base URL",
  "Start When I Open a PR": "打开 PR 时启动",
  "Post to Slack": "发布到 Slack",
  "Slack Channel": "Slack 频道",
  "Ignore branch difference": "忽略分支差异",
  "Apply Intelligently": "智能应用",
  "Apply to Specific Files": "应用到指定文件",
  "Apply Manually": "手动应用",
  "Ignore Symlinks in Cursor Ignore Search": "在忽略搜索中跳过符号链接",
  "Manually Sent Messages from Queue": "从队列手动发送的消息",
  "Generate an implementation plan": "生成实现计划",
  "Pinpoint the root cause of an issue": "定位问题的根本原因",
  "Answer questions without making edits": "只回答问题，不修改代码",
  "Orchestrate multiple subagents in parallel": "并行编排多个子 Agent",
  "Use development environment": "使用开发环境",
  "Use production environment": "使用生产环境",
  "Use full local environment (non-VM running locally)": "使用完整本地环境（非虚拟机，在本机运行）",
  "All team members can access": "所有团队成员都可访问",
  "Anyone with the link can access": "任何有链接的人都可以访问",
  "Select who can see and use plugins from this team marketplace": "选择谁可以查看和使用此团队市场中的插件",
  "Automatically update plugins when changes are pushed to the repository": "向仓库推送更改后自动更新插件",
  "Let any team member publish plugins to this marketplace. When off, only team admins can publish.": "允许任何团队成员向此市场发布插件。关闭后仅团队管理员可发布。",
  "Cursor keeps a synced copy of this repository and serves plugins from it, so team members can use the marketplace without GitHub access to the source repo. Access is controlled by Marketplace Access.": "Cursor 会同步保存此仓库的副本并从中提供插件，团队成员无需 GitHub 访问源仓库即可使用市场。访问权限由“市场访问”控制。",
  "Fetch marketplace plugins from the GitHub repository": "从 GitHub 仓库获取市场插件",
  "This marketplace and its access settings will be removed. The source repository won't be affected.": "将移除此市场及其访问设置，不会影响源仓库。",
  "Plugins bundle rules, skills, subagents, commands, MCP servers, and hooks into one installable package.": "插件把规则、技能、子 Agent、命令、MCP 服务器和 Hooks 打包成一个可安装包。",
  "Creates a new MCP configuration with example servers": "创建带示例服务器的新 MCP 配置",
  "Suggest a follow-up for the Agent": "为 Agent 建议跟进内容",
  "Show Add to Chat & Quick Edit buttons when selecting code": "选中代码时显示“添加到聊天”和“快速编辑”按钮",
  "We've introduced a new home for all the ways to customize Cursor.": "我们为 Cursor 的各种自定义方式提供了新入口。",
  "Entry-level plan with access to premium models, unlimited Tab completions, and more.": "入门套餐，可使用高级模型、无限 Tab 补全等功能。",
  "Accelerate development, shared knowledge, and context across your team": "加速开发，并在团队中共享知识和上下文",
  "Automatically resume working on agents and their subagents after a reload or restart": "重新加载或重启后自动继续处理 Agent 及其子 Agent",
  "Show notifications for less urgent issues": "为不太紧急的问题显示通知",
  "Include changes from Git submodules in the review": "在审查中包含 Git 子模块的更改",
  "Include untracked files (new files not yet added to Git) in the review": "在审查中包含未跟踪文件（尚未加入 Git 的新文件）",
  "Choose between quick or more thorough, higher-cost analysis": "在快速分析和更彻底、成本更高的分析之间选择",
  "Disable AI features in specific repositories based on file pattern": "根据文件模式在特定仓库中禁用 AI 功能",
  "Sign in to get started with Cursor's AI features": "登录以开始使用 Cursor 的 AI 功能",
  "Manage your account and billing": "管理账户和账单",
  "Configure font, formatting, minimap and more": "配置字体、格式化、缩略图等",
  "Configure keyboard shortcuts": "配置键盘快捷方式",
  "Import settings, extensions, and keybindings from VS Code": "从 VS Code 导入设置、扩展和键盘快捷方式",
  "Choose how much detail Agent tool calls show in the conversation": "选择 Agent 工具调用在对话中显示的详细程度",
  "Show rotating tips on the empty screen": "在空白屏幕上轮播提示",
  "Controls which windows Cursor restores on startup": "控制 Cursor 启动时还原哪些窗口",
  "Show system notifications when Agent completes or needs attention": "当 Agent 完成或需要关注时显示系统通知",
  "Also show the approval banner while Cursor is focused; the request card in the agent conversation always shows": "Cursor 处于前台时也显示批准横幅；Agent 对话中的请求卡片始终显示",
  "Show Cursor in the menu bar": "在菜单栏中显示 Cursor",
  "Show Cursor in the system tray": "在系统托盘中显示 Cursor",
  "Play a sound when Agent finishes responding": "Agent 完成回复时播放提示音",
  "Account email shown on the profile page": "资料页上显示的账户邮箱",
  "Upload or remove the profile photo": "上传或移除头像",
  "Name shown on the public profile page": "公开资料页上显示的姓名",
  "Claim a handle for your public profile page": "为公开资料页设置用户名",
  "Social and website links on the public profile page": "公开资料页上的社交和网站链接",
  "Make the cursor.com profile page visible to anyone with the link": "让任何有链接的人都能看到 cursor.com 资料页",
  "Match the active theme to your OS dark/light setting": "让当前主题跟随操作系统的深色/浅色设置",
  "Choose which theme to use": "选择要使用的主题",
  "Choose the theme used when your system is in light mode": "系统处于浅色模式时使用的主题",
  "Choose the theme used when your system is in dark mode": "系统处于深色模式时使用的主题",
  "Switch to a high contrast theme when your OS is in a high contrast mode": "操作系统处于高对比度模式时切换到高对比度主题",
  "Choose the theme used when your system is in light high contrast mode": "系统处于浅色高对比度模式时使用的主题",
  "Choose the theme used when your system is in dark high contrast mode": "系统处于深色高对比度模式时使用的主题",
  "Create your own themes, tweak the vibe, and import your favorites": "创建自己的主题、调整风格并导入收藏",
  "Choose a tint color": "选择着色",
  "Control how strongly the tint is applied": "控制着色强度",
  "Replace translucent surfaces with opaque backgrounds": "用不透明背景替换半透明表面",
  "Adjust how much detail is shown for tool calls": "调整工具调用显示的详细程度",
  "Font size for the Cursor user interface": "Cursor 界面字体大小",
  "Font size for code editors and diffs": "代码编辑器和差异视图的字体大小",
  "Override the Cursor user interface typeface": "覆盖 Cursor 界面字体",
  "Override the font for code editors and diffs": "覆盖代码编辑器和差异视图的字体",
  "Use native macOS font anti-aliasing": "使用 macOS 原生字体抗锯齿",
  "Minimize interface animations": "减少界面动画",
  "Allow the agent to celebrate with a shower of confetti": "允许 Agent 用礼花庆祝",
  "Partially mask your email address in the Cursor user interface": "在 Cursor 界面中部分隐藏邮箱地址",
  "Set a fixed amount or make on-demand usage unlimited": "设置固定额度，或将对需用量设为不限",
  "Context-aware, multi-line suggestions around your cursor based on recent edits": "基于最近编辑、在光标附近提供感知上下文的多行建议",
  "When to show the usage summary at the bottom of the chat pane": "何时在聊天窗格底部显示用量摘要",
  "Adjust the conversation text size": "调整对话文字大小",
  "Where new agents start by default": "新 Agent 的默认启动位置",
  "Adjust the default behavior of sending a message while Agent is running": "调整 Agent 运行时发送消息的默认行为",
  "What sending a message while Agent is running does": "Agent 运行时发送消息会做什么",
  "What the queued-message Send Now action does": "队列消息的“立即发送”操作会做什么",
  "Contextual suggestions while prompting Agent": "向 Agent 提问时的上下文建议",
  "Allow agent to switch to modes without asking. When off, skips if unanswered within 15 seconds.": "允许 Agent 在不询问的情况下切换模式。关闭后，若 15 秒内未回答则跳过。",
  "Custom words that submit a voice prompt": "用于提交语音提示的自定义词",
  "Allow Agent to search the web for relevant information": "允许 Agent 在网上搜索相关信息",
  "Allow Agent to fetch content from URLs": "允许 Agent 抓取 URL 中的内容",
  "Wait indefinitely; otherwise skip prompts after 30 seconds": "无限期等待；否则 30 秒后跳过提示",
  "Control whether agents can read files outside the workspace without approval.": "控制 Agent 是否可以在未经批准的情况下读取工作区外的文件。",
  "File paths and glob patterns agents can read without approval.": "Agent 无需批准即可读取的文件路径和 glob 模式。",
  "Use legacy terminal tool on unsupported shells": "在不支持的 shell 上使用旧版终端工具",
  "Automatically parse links pasted into Quick Edit": "自动解析粘贴到快速编辑中的链接",
  "Enable language server by default to provide code intelligence in workspaces": "默认启用语言服务器，为工作区提供代码智能",
  "Enable language server by default to provide code intelligence in agent worktree workspaces": "默认启用语言服务器，为 Agent Worktree 工作区提供代码智能",
  "Maximum local workspaces that can run language servers at the same time": "可同时运行语言服务器的本地工作区数量上限",
  "Maximum remote workspaces that can run language servers at the same time": "可同时运行语言服务器的远程工作区数量上限",
  "Show inline diff decorations in the editor": "在编辑器中显示内联差异装饰",
  "Automatically format files when Agent finishes": "Agent 完成后自动格式化文件",
  "Cursor syncs your local skills so they can be used with Cloud Agents": "Cursor 会同步本地技能，以便云端 Agent 使用",
  "Cursor syncs your local skills so they can be used with Cloud Agents. Turn this off to disable syncing.": "Cursor 会同步本地技能，以便云端 Agent 使用。关闭此项可停止同步。",
  "Show Add to Chat and Quick Edit buttons": "显示“添加到聊天”和“快速编辑”按钮",
  "Show the Cmd/Ctrl+K hint in Terminal": "在终端中显示 Cmd/Ctrl+K 提示",
  "Use the preview box instead of shell streaming": "使用预览框而不是 shell 流式输出",
  "Choose the model used by Explore subagent for initial research": "选择探索子 Agent 用于初步研究的模型",
  "Configure the local agent LLM gateway": "配置本地 Agent LLM 网关",
  "Open pull request links inside Cursor or the default browser": "在 Cursor 或默认浏览器中打开拉取请求链接",
  "Automatically review your changes for issues after each commit": "每次提交后自动审查更改中的问题",
  "Off disables Self-driving for PRs owned by this account.": "关闭后，将禁用此账户所拥有 PR 的自动驾驶。",
  "Starts Self-driving when a PR opens on an enabled repository.": "在已启用的仓库中打开 PR 时启动自动驾驶。",
  "Used when Self-driving starts automatically from account defaults.": "当自动驾驶按账户默认设置自动启动时使用。",
  "Posts Self-driving updates to Slack when there are suggestions for PRs.": "当 PR 有建议时，将自动驾驶更新发布到 Slack。",
  "Pick a Slack channel or use DMs.": "选择 Slack 频道或使用私信。",
  "Automatically import agent configs from other tools": "从其他工具自动导入 Agent 配置",
  "Sync chats and continue them in Cursor": "同步聊天并在 Cursor 中继续",
  "Files to exclude from indexing in addition to .gitignore": "除 .gitignore 外还要从索引中排除的文件",
  "Apply .cursorignore files to subdirectories": "将 .cursorignore 应用到子目录",
  "Skip symlinks during discovery": "发现时跳过符号链接",
  "Configure HTTP compatibility for proxies and VPNs": "为代理和 VPN 配置 HTTP 兼容性",
  "Domains required for Cursor": "Cursor 所需的域名",
  "Check connectivity to all Cursor services": "检查与所有 Cursor 服务的连接",
  "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",
  "Maximum retained Cursor-managed worktrees": "保留的 Cursor 管理 Worktree 数量上限",
  "Maximum aggregate worktree size": "Worktree 总大小上限",
  "Recommended to ensure correct base for changes": "建议启用以确保更改基于正确的基准",
  "Apply to every chat and cmd-k session": "应用到每个聊天和 Cmd+K 会话",
  "When Agent decides it's relevant based on description": "当 Agent 根据描述判断相关时",
  "When file matches a specified pattern": "当文件匹配指定模式时",
  "Control which network requests are allowed when commands run in the sandbox. Edit allowed/denied domains in sandbox.json in your workspace.": "控制沙箱中命令运行时允许的网络请求。可在工作区的 sandbox.json 中编辑允许/拒绝的域名。",
  "Wrap long lines in Agent conversation code blocks": "在 Agent 对话代码块中换行显示长行",
  "Use themed background colors for inline code diffs": "为内联代码差异使用主题化背景色",
  "Steer the agent without stopping it": "引导 Agent 而不停止它",
  "Stop the agent and send the message": "停止 Agent 并发送消息",
  "Send after Agent finishes": "等 Agent 完成后再发送",
  "What model new agents use by default": "新 Agent 默认使用的模型",
  "Enable auto import for Python. This is a beta feature.": "为 Python 启用自动导入。这是测试版功能。",
  "Allow Tab to trigger while in a comment region": "在注释区域中也允许触发 Tab",
  "If you enable Privacy Mode, none of your questions or code will ever be stored by us or any third-party.": "如果启用隐私模式，你的问题和代码都不会被我们或任何第三方存储。",
  "On-demand spending is currently disabled": "按需支出当前已禁用",
  "Set a fixed amount or make it unlimited.": "设置固定额度，或设为不限。",
  "Enable on-demand usage to go beyond your plan's included usage. Requires a paid plan.": "启用以超出套餐包含用量的按需用量。需要付费套餐。",
  "Spend limits for team plans are managed by team admins in the dashboard": "团队套餐的支出上限由团队管理员在控制台中管理",
  "Disable HTTP/2 for all requests, and use HTTP/1.1 instead. This increases resource utilization and latency, but is useful if you're behind a corporate proxy that blocks HTTP/2.": "对所有请求禁用 HTTP/2，改用 HTTP/1.1。这会增加资源占用和延迟，但适用于拦截 HTTP/2 的公司代理。",
  "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.": "建议使用 HTTP/2 以获得低延迟流式传输。在某些公司代理和 VPN 环境中，可能需要降低兼容模式。",
  "Automatically index repositories locally to speed up Grep searches. Reload the window after changing this setting.": "在本地为仓库建立索引以加快 Grep 搜索。更改此设置后请重新加载窗口。",
  "Automatically open http and https links in the Browser Tab": "在浏览器标签页中自动打开 http 和 https 链接",
  "Automatically open localhost links in the Browser Tab": "在浏览器标签页中自动打开 localhost 链接",
  "Get started with Cursor.": "开始使用 Cursor。",
  "Ask Cursor questions about your codebase": "向 Cursor 询问代码库相关问题",
  "Create detailed plans for accomplishing tasks": "为完成任务创建详细计划",
  "Create structured plans with implementation steps": "创建带实现步骤的结构化计划",
  "Coordinate long-horizon tasks with delegated subagents": "通过委派子 Agent 协调长期任务",
  "An AI teammate that works in your tools and comes back with finished work.": "一个能在你的工具中工作并带回完成成果的 AI 队友。",
  "AI teammates you can give real work to": "可以把实际工作交给他们的 AI 队友",
  "Model Context Protocol servers connect Cursor to external tools and data sources like Linear, Figma, and Notion.": "MCP 服务器把 Cursor 连接到 Linear、Figma、Notion 等外部工具和数据源。",
  "Hooks run custom scripts at lifecycle events to observe, control, and extend the agent loop.": "Hooks 在生命周期事件上运行自定义脚本，用于观察、控制和扩展 Agent 循环。",
  "Commands are reusable prompts you invoke with /name to standardize common workflows across your team.": "命令是可用 /名称 调用的可复用提示，用于在团队中标准化常用工作流。",
  "Add plugins or import from GitHub to make them available for your team.": "添加插件或从 GitHub 导入，以便团队使用。",
  "Change Cursor editor preferences.": "更改 Cursor 编辑器首选项。",
  "Change Cursor CLI preferences.": "更改 Cursor CLI 首选项。",
  "Connect GitHub/GitLab, manage team and user settings, and configure environments": "连接 GitHub/GitLab，管理团队和用户设置，并配置环境",
  "Prefix for new branches created by Agent (e.g., cursor/, username/)": "Agent 新建分支的前缀（例如 cursor/、username/）",
  "Prefix for new Agent branches": "新 Agent 分支的前缀",
  "Enable or disable Self-driving for PRs owned by this account": "启用或禁用此账户所拥有 PR 的自动驾驶",
  "Start Self-driving automatically for enabled repositories": "为已启用的仓库自动启动自动驾驶",
  "Choose whether automatically started agents suggest or apply changes": "选择自动启动的 Agent 是建议更改还是直接应用",
  "Post Self-driving updates to Slack": "将自动驾驶更新发布到 Slack",
  "Run Private Inference in a separate local process to isolate it from remote workspace activity. Reload Cursor after changing this setting.": "在单独的本地进程中运行私有推理，使其与远程工作区活动隔离。更改后请重新加载 Cursor。",
  "Maximum number of Cursor-managed worktrees to keep across all workspaces. Older worktrees are removed first. Default is 25.": "所有工作区中保留的 Cursor 管理 Worktree 数量上限。较旧的会先被删除。默认 25。",
  "Maximum total size in GB for the Cursor worktrees directory across all workspaces. Set to 0 to disable this limit.": "所有工作区中 Cursor Worktree 目录的总大小上限（GB）。设为 0 可禁用此限制。",
  "Suggest edits like new lines and indentation that modify whitespace only": "建议仅修改空白的编辑，例如新行和缩进",
  "Allow agent to switch to modes like Plan or Debug without asking. When off, Cursor asks first, but skips if unanswered within 15 seconds.": "允许 Agent 在不询问的情况下切换到计划或调试等模式。关闭后 Cursor 会先询问，若 15 秒内未回答则跳过。",
  "Choose which models appear in the model picker": "选择模型选择器中显示哪些模型",
  "Choose the default behavior of messages sent while Agent is working": "选择 Agent 工作时发送消息的默认行为",
  "Choose the default behavior of messages sent from the queue": "选择从队列发送消息的默认行为",
  "Disable Cursor Tab for these languages": "对这些语言禁用 Cursor Tab",
  "Glob patterns for files where Cursor Tab will not suggest": "不提供 Cursor Tab 建议的文件 glob 模式",
  "Enable partial accepts for Cursor Tab, using the editor.action.inlineSuggest.acceptNextWord keybinding": "启用 Cursor Tab 部分接受，使用 editor.action.inlineSuggest.acceptNextWord 快捷键",
  "Enable performance protection for inline diffs. When enabled, inline diff decorations will be suppressed if there are too many changes to prevent editor unresponsiveness.": "启用内联差异性能保护。更改过多时会抑制内联差异装饰，以免编辑器卡顿。",
  "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.": "Agent 可自动抓取的域名。使用 * 表示全部域名，使用 *.example.com 表示通配子域。",
  "Move Cursor rules and commands into Agent Skills.": "将 Cursor 规则和命令迁移到 Agent 技能。",
  "Great for individual developers": "适合个人开发者",
  "More power for demanding projects": "适合要求更高的项目",
  "Maximum power and flexibility": "最高性能和灵活性",
  "Loading Cloud Agents settings...": "正在加载云端 Agent 设置…",
  "Cloud Agents require a Git repository in an open folder.": "云端 Agent 需要在已打开的文件夹中使用 Git 仓库。",
  "Cloud Agents require data storage to function.": "云端 Agent 需要数据存储才能运行。",
  "Can't use Cursor": "无法使用 Cursor",
};

const skip = new Set(["Local", "Cloud", "Handle", "Links", "Colors", "Motion", "Fun", "Layout", "Conversation", "Appearance", "LSP", "Cleanup", "Gateway", "Open File"]);
for (const key of skip) delete extra[key];

let added = 0;
for (const [en, zh] of Object.entries(extra)) {
  if (!map[en]) {
    map[en] = zh;
    added += 1;
  }
}
fs.writeFileSync("payload/hardcoded-zh.json", JSON.stringify(map, null, 2) + "\n");

const contexts = JSON.parse(fs.readFileSync("payload/hardcoded-context.json", "utf8"));
const extraContexts = [
  ["async _isPure(){const e=this.productService.checksums||{};", "async _isPure(){return{isPure:!0,proof:[]};const e=this.productService.checksums||{};"],
  ["_showNotification(){const e=this.productService.checksumFailMoreInfoUrl", "_showNotification(){return;const e=this.productService.checksumFailMoreInfoUrl"],
  ["if(e||await this._isExplainedByPendingUpdate())return;this.logService.warn(`", "if(true||e||await this._isExplainedByPendingUpdate())return;this.logService.warn(`"],
  ["title:{value:\"View\",original:\"View\"", "title:{value:\"查看\",original:\"View\""],
  ["label:\"Preferences\"", "label:\"首选项\""],
  ["label:\"Keyboard Shortcuts\"", "label:\"键盘快捷方式\""],
  ["label:\"Layout\"", "label:\"布局\""],
  ["label:\"Notifications\"", "label:\"通知\""],
  ["label:\"Window Restoration\"", "label:\"窗口还原\""],
  ["label:\"Typography\"", "label:\"排版\""],
  ["label:\"Motion\"", "label:\"动效\""],
  ["label:\"Colors\"", "label:\"颜色\""],
  ["label:\"Conversation\"", "label:\"对话\""],
  ["label:\"Cursor Tab\"", "label:\"Cursor Tab\""],
  ["label:\"Status Bar\"", "label:\"状态栏\""],
  ["label:\"Codebase\"", "label:\"代码库\""],
  ["label:\"Pull Requests\"", "label:\"拉取请求\""],
  ["label:\"Gateway\"", "label:\"网关\""],
  ["label:\"Cleanup\"", "label:\"清理\""],
  ["label:\"LSP\"", "label:\"语言服务\""],
  ["label:\"Ignore Files\"", "label:\"忽略文件\""],
  ["title:\"Appearance\"", "title:\"外观\""],
  ["label:\"Appearance\"", "label:\"外观\""],
  ["children:\"Steer\"", "children:\"引导\""],
  ["children:\"Interrupt\"", "children:\"中断\""],
  ["children:\"Queue\"", "children:\"排队\""],
  ["label:\"Steer\"", "label:\"引导\""],
  ["label:\"Interrupt\"", "label:\"中断\""],
  ["label:\"Queue\"", "label:\"排队\""],
];

let contextAdded = 0;
const seen = new Set(contexts.map((pair) => pair[0]));
for (const pair of extraContexts) {
  if (seen.has(pair[0]) || pair[0] === pair[1]) continue;
  contexts.push(pair);
  seen.add(pair[0]);
  contextAdded += 1;
}
fs.writeFileSync("payload/hardcoded-context.json", JSON.stringify(contexts, null, 2) + "\n");
console.log(`map +${added} total=${Object.keys(map).length} contexts +${contextAdded} total=${contexts.length}`);
