import "./lib/win-console.mjs";
import fs from "node:fs";

const map = JSON.parse(fs.readFileSync("payload/hardcoded-zh.json", "utf8"));
const extra = {
  "Submit with Ctrl + Enter": "使用 Ctrl + Enter 提交",
  "Custom words that submit a voice prompt. Spaces and punctuation are ignored.": "用于提交语音提示的自定义词。空格和标点会被忽略。",
  "Choose how Agents run tools like command execution, MCP, and file writes.": "选择 Agent 如何运行命令执行、MCP 和文件写入等工具。",
  "A classifier will run for each action and decide whether it's safe to execute this command. Allowlists are still respected.": "每个操作都会运行分类器，判断该命令是否可以安全执行。允许列表仍然生效。",
  "Learn more": "了解更多",
  "Auto-Review": "自动审查",
  "Auto-Review (with Sandbox)": "自动审查（含沙箱）",
  "Run Everything": "全部运行",
  "Run Everything (Unsandboxed)": "全部运行（无沙箱）",
  "Prevent Agent from deleting files automatically": "阻止 Agent 自动删除文件",
  "Prevent Agent from creating or modifying files outside of the workspace automatically": "阻止 Agent 自动在工作区外创建或修改文件",
  "You can configure Shell, MCP and Fetch allowlists for Auto mode. However, Auto works well without these.": "可以为自动模式配置 Shell、MCP 和 Fetch 允许列表。不过不配置时自动模式通常也能正常工作。",
  "Applying Changes": "应用更改",
  "Show inline diff decorations in the editor instead of only showing changes in the review panel": "在编辑器中显示内联差异装饰，而不只在审查面板中显示更改",
  "Automatically format files when the agent finishes": "Agent 完成后自动格式化文件",
  "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations": "在 Agent 模式中使用旧版终端工具，适用于不受支持的 shell 配置",
  "Use a preview box instead of streaming responses directly into the shell": "使用预览框，而不是把回复直接流式写入 shell",
  "Adjust Plan": "调整套餐",
  "Unlock 3x more usage on Agent & more": "解锁 3 倍 Agent 用量及更多权益",
  "Additional usage beyond limits consumes Other Models quota or on-demand spend.": "超出限额的额外用量会消耗其他模型配额或按需支出。",
  "Additional usage beyond limits consumes on-demand spend.": "超出限额的额外用量会消耗按需支出。",
  "Open a Git repository": "打开 Git 仓库",
  "Please open a folder to use background agents.": "请打开一个文件夹以使用后台 Agent。",
  "Background agents only work in folders with a git repository. Please open a folder that contains a git repository.": "后台 Agent 只能在包含 Git 仓库的文件夹中使用。请打开一个 Git 仓库文件夹。",
  "Get Started": "开始使用",
  "PR Link Destination": "PR 链接打开位置",
  "Open pull request links inside Cursor or in the default browser": "在 Cursor 内或默认浏览器中打开拉取请求链接",
  "Inside Cursor": "在 Cursor 内",
  "Default Browser": "默认浏览器",
  "Commit Attribution": "提交归属",
  "PR Attribution": "PR 归属",
  "Mark pull requests as made with Cursor": "将拉取请求标记为使用 Cursor 完成",
  "Browser Automation": "浏览器自动化",
  "Connected to Browser Tab": "已连接到浏览器标签页",
  "Browser automation disabled": "浏览器自动化已关闭",
  "Browser Protection": "浏览器保护",
  "Prevent Agent from automatically running Browser tools": "阻止 Agent 自动运行浏览器工具",
  "Open Local Links in Cursor Browser": "在 Cursor 浏览器中打开本地链接",
  "Open Web Links in Cursor Browser": "在 Cursor 浏览器中打开网页链接",
  "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.": "这些域名必须可访问，Cursor 才能正常工作。请将它们加入防火墙或代理允许列表。",
  "Copy Domains": "复制域名",
  "Run Diagnostic": "运行诊断",
  "Partial Accepts": "部分接受",
  "Whitespace-Only Suggestions": "仅空白建议",
  "Ignored Files": "忽略的文件",
  "View included files.": "查看已包含的文件。",
  "Hierarchical Cursor Ignore": "分层 Cursor Ignore",
  "Cursor Default": "Cursor 默认",
  "Last Used": "上次使用",
  "Open View": "打开视图",
  "Open View...": "打开视图...",
  "Source Control": "源代码管理",
  "Open IDE": "打开 IDE",
  "New Browser": "新建浏览器",
  "View License": "查看许可证",
  "Zoom In": "放大",
  "Zoom Out": "缩小",
  "Reset Zoom": "重置缩放",
  "Command Palette": "命令面板",
  "Command Palette...": "命令面板...",
  "Select All": "全选",
  "New Project": "新建项目",
  "Show Chat History": "显示聊天记录",
  "CURRENT PLAN": "当前套餐",
  "Current Plan": "当前套餐",
  "UPGRADE AVAILABLE": "可升级",
  "Upgrade Available": "可升级",
  "Included in Pro": "Pro 已包含",
  "On Home": "在首页",
  "Auto-Review": "自动审查",
  "Disabled": "已禁用",
  "Save": "保存",
  "Edit": "编辑",
  "Show": "显示",
  "Explorer": "资源管理器",
  "Problems": "问题",
  "Output": "输出",
  "Conversation": "对话",
  "Branches": "分支",
  "Other Models": "其他模型",
  "Cursor Models": "Cursor 模型",
  "Includes Cursor Grok and Composer": "包含 Cursor Grok 和 Composer",
  "Agents Window Button: Enabled": "Agents 窗口按钮: 已启用",
  "Command Palette › Experimental: Ask Chat Location": "命令面板 › 实验性: 询问聊天位置",
  "Command Palette › Experimental: Enable Natural Language Search": "命令面板 › 实验性: 启用自然语言搜索",
  "Command Palette › Experimental: Suggest Commands": "命令面板 › 实验性: 建议命令",
  "Command Palette: History": "命令面板: 历史记录",
  "Command Palette: Preserve Input": "命令面板: 保留输入",
  "Editor Associations": "编辑器关联",
  "Editor Large File Confirmation": "编辑器: 大文件确认",
  "Enable Experiments": "启用实验",
  "Experimental › Share: Enabled": "实验性 › 共享: 已启用",
  "External Browser": "外部浏览器",
  "External Uri Openers": "外部 URI 打开程序",
  "Hover: Delay": "悬停: 延迟",
  "Layout Control: Enabled": "布局控件: 已启用",
  "Layout Control: Type": "布局控件: 类型",
  "List: Default Find Match Type": "列表: 默认查找匹配类型",
  "List: Default Find Mode": "列表: 默认查找模式",
  "List: Fast Scroll Sensitivity": "列表: 快速滚动灵敏度",
  "List: Horizontal Scrolling": "列表: 水平滚动",
  "List: Mouse Wheel Scroll Sensitivity": "列表: 鼠标滚轮滚动灵敏度",
  "List: Multi Select Modifier": "列表: 多选修饰键",
  "Startup Editor": "启动编辑器",
  "Trusted Domains: Prompt In Trusted Workspace": "受信任域名: 在受信任工作区中提示",
  "Welcome Page › Walkthroughs: Open On Install": "欢迎页 › 演练: 安装时打开",
  "Activity Bar: Icon Click Behavior": "活动栏: 图标单击行为",
  "Activity Bar: Location": "活动栏: 位置",
  "Activity Bar: Orientation": "活动栏: 方向",
  "Color Customizations": "颜色自定义",
  "Color Theme": "颜色主题",
  "Auto Detect Color Scheme": "自动检测颜色主题",
  "Auto Detect High Contrast": "自动检测高对比度",
  "Close When Empty": "为空时关闭",
  "Command Center": "命令中心",
  "Confirm Before Close": "关闭前确认",
  "Confirm Save Untitled Workspace": "确认保存无标题工作区",
  "Controls Style": "控件样式",
  "Density: Editor Tab Height": "密度: 编辑器选项卡高度",
  "Dialog Style": "对话框样式",
  "Accessibility › Signal Options: Debounce Position Changes": "辅助功能 › 信号选项: 对位置更改去抖动",
  "Accessibility › Signal Options › Experimental › Delays: Error At Position": "辅助功能 › 信号选项 › 实验性 › 延迟: 位置上的错误",
  "Accessibility › Signal Options › Experimental › Delays: Warning At Position": "辅助功能 › 信号选项 › 实验性 › 延迟: 位置上的警告",
  "Accessibility › Signal Options: Volume": "辅助功能 › 信号选项: 音量",
  "Accessibility › Signals: Chat Edit Modified File": "辅助功能 › 信号: 聊天编辑已修改的文件",
  "Accessibility › Signals: Chat Request Sent": "辅助功能 › 信号: 已发送聊天请求",
  "Prompt For Local File Protocol Handling": "本地文件协议处理提示",
  "Prompt For Remote File Protocol Handling": "远程文件协议处理提示",
  "Restrict UNCAccess": "限制 UNC 访问",
  "Trust: Banner": "信任: 横幅",
  "Trust: Empty Window": "信任: 空窗口",
  "Trust: Enabled": "信任: 已启用",
  "Trust: Startup Prompt": "信任: 启动提示",
  "Trust: Untrusted Files": "信任: 不受信任的文件",
  "Experimental: Serialization": "实验性: 序列化",
  "Paste Images As Attachments: Enabled": "将图像粘贴为附件: 已启用",
  "Auto Navigate Next Conflict: Enabled": "自动转到下一个冲突: 已启用",
  "Code Lens: Enabled": "CodeLens: 已启用",
  "Decorators: Enabled": "装饰器: 已启用",
  "Diff View Position": "差异视图位置",
  "References: Preferred Location": "引用: 首选位置",
  "Completion: Complete Property With Semicolon": "补全: 使用分号完成属性",
  "Apply .cursorignore files to all subdirectories. Changing this setting requires restarting Cursor.": "将 .cursorignore 应用到所有子目录。更改此设置后需要重启 Cursor。",
  "Use with caution. Skip symlinks during .cursorignore file discovery. Enable only when all .cursorignore files are reachable without symlinks. Changing this setting requires restarting Cursor.": "请谨慎使用。在发现 .cursorignore 时跳过符号链接。仅当所有 .cursorignore 都可不经符号链接访问时启用。更改后需要重启 Cursor。",
  "By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.": "默认接收稳定版更新通知。早期访问的预发布版本可能不适合生产环境。",
  "Files to exclude from indexing in addition to .gitignore": "除 .gitignore 外还要从索引中排除的文件",
  "Automatically index repositories to speed up Grep searches. All data is stored locally.": "自动为仓库建立索引以加快 Grep 搜索。所有数据都存储在本地。",
  "Automatically import necessary modules for TypeScript": "自动导入 TypeScript 所需的模块",
  "Accept the next word of a suggestion via Ctrl+RightArrow": "使用 Ctrl+RightArrow 接受建议中的下一个词",
  "Mark Agent commits as 'Made with Cursor'": "将 Agent 提交标记为“Made with Cursor”",
  "Choose Origin (cursor.com/codebase), GitHub, or Graphite for pull request links on web and desktop": "选择 Origin（cursor.com/codebase）、GitHub 或 Graphite，用于网页和桌面上的拉取请求链接",
  "Choose Origin (cursor.com/codebase) or GitHub for GitHub pull request links on web and desktop": "选择 Origin（cursor.com/codebase）或 GitHub，用于网页和桌面上的 GitHub 拉取请求链接",
};

const skip = new Set(["Edit", "Show", "Save", "Disabled", "Explorer", "Problems", "Output", "Conversation", "Branches"]);
for (const key of skip) delete extra[key];

let added = 0;
for (const [en, zh] of Object.entries(extra)) {
  if (!map[en]) {
    map[en] = zh;
    added += 1;
  }
}
fs.writeFileSync("payload/hardcoded-zh.json", JSON.stringify(map, null, 2) + "\n");

const contexts = JSON.parse(fs.readFileSync("payload/hardcoded-context.json", "utf8"));
const extraContexts = [
  ["Prevent Agent from deleting files automatically", "阻止 Agent 自动删除文件"],
  ["Prevent Agent from creating or modifying files outside of the workspace automatically", "阻止 Agent 自动在工作区外创建或修改文件"],
  ["Automatically jump to the next diff when accepting changes with ${Ei?\"\\u2318\":\"Ctrl+\"}Y", "接受更改后使用 ${Ei?\"\\u2318\":\"Ctrl+\"}Y 自动跳到下一个差异"],
  ["Automatically parse links when pasted into Quick Edit (${Ei?\"\\u2318\":\"Ctrl+\"}K) input", "粘贴到快速编辑（${Ei?\"\\u2318\":\"Ctrl+\"}K）时自动解析链接"],
  ["Show a hint for ${Ei?\"\\u2318\":\"Ctrl+\"}K in the Terminal", "在终端中显示 ${Ei?\"\\u2318\":\"Ctrl+\"}K 提示"],
  ["Preview Box for Terminal ${Ei?\"\\u2318\":\"Ctrl+\"}K", "终端 ${Ei?\"\\u2318\":\"Ctrl+\"}K 预览框"],
  ["Accept the next word of a suggestion via ${u}", "通过 ${u} 接受建议中的下一个词"],
  ["Automatically import necessary modules for ${k}", "自动导入 ${k} 所需的模块"],
  ['title:"Applying Changes"', 'title:"应用更改"'],
  ['accessibleLabel:"Applying Changes"', 'accessibleLabel:"应用更改"'],
  ['label:"PR Link Destination"', 'label:"PR 链接打开位置"'],
  ['"aria-label":"PR Link Destination"', '"aria-label":"PR 链接打开位置"'],
  ['label:"Partial Accepts"', 'label:"部分接受"'],
  ['label:"Ignored Files"', 'label:"忽略的文件"'],
  ['ariaLabel:"Ignored Files"', 'ariaLabel:"忽略的文件"'],
  ['label:"Hierarchical Cursor Ignore"', 'label:"分层 Cursor Ignore"'],
  ['label:"Browser Automation"', 'label:"浏览器自动化"'],
  ['label:"Browser Protection"', 'label:"浏览器保护"'],
  ['label:"Whitespace-Only Suggestions"', 'label:"仅空白建议"'],
  ['label:"Cursor Default"', 'label:"Cursor 默认"'],
  ['label:"Last Used"', 'label:"上次使用"'],
  ['label:"Inside Cursor"', 'label:"在 Cursor 内"'],
  ['label:"Default Browser"', 'label:"默认浏览器"'],
  ['label:"Auto-Review"', 'label:"自动审查"'],
  ["Usage limits reset on ", "用量限额重置日期："],
  ['title:"Open a Git repository"', 'title:"打开 Git 仓库"'],
  ['actionTitle:"Open Folder"', 'actionTitle:"打开文件夹"'],
  ['title:"Get Started"', 'title:"开始使用"'],
  ['title:"Attribution"', 'title:"归属"'],
  ['label:"Required Domains"', 'label:"必需域名"'],
  ["value:\"explorer\",title:S(", "value:\"explorer\",title:S("],
];

let contextAdded = 0;
const seen = new Set(contexts.map((pair) => pair[0]));
for (const pair of extraContexts) {
  if (pair[0] === pair[1]) continue;
  if (seen.has(pair[0])) continue;
  contexts.push(pair);
  seen.add(pair[0]);
  contextAdded += 1;
}
fs.writeFileSync("payload/hardcoded-context.json", JSON.stringify(contexts, null, 2) + "\n");
console.log(`map +${added} total=${Object.keys(map).length} contexts +${contextAdded} total=${contexts.length}`);
